name: Create terraform plan for Identity Center

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  pull-requests: write

env:
  TERRAFORM_FILES_PATH: .
  GOOGLE_BACKEND_CREDENTIALS: "${{ github.workspace }}/credentials.json"

jobs:
  plan:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Prepare GCS Credentials
        run: |
          set -xeu
          echo "${{ secrets.GITHUB_TOKEN }}" > $GOOGLE_BACKEND_CREDENTIALS
      - run: |
          set -xeu
          cat $GOOGLE_BACKEND_CREDENTIALS

      - name: terraform fmt
        uses: dflook/terraform-fmt-check@v1
        with:
          path: ${{env.TERRAFORM_FILES_PATH}}

      - name: terraform validate
        uses: dflook/terraform-validate@v1
        with:
          path: ${{env.TERRAFORM_FILES_PATH}}

      - name: terraform plan
        uses: dflook/terraform-plan@v1
        with:
          path: ${{env.TERRAFORM_FILES_PATH}}
